spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fo191r/microservices_config.git
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  port: 8888
